version: "3"
services:
  reverseproxy:
    build:
      context: ./udagram-reverseproxy
    image: serenalin7749/reverseproxy
  backend_user:
    build:
      context: ./udagram-api-user
    image: serenalin7749/udagram-api-user
  backend_feed:
    build:
      context: ./udagram-api-feed
    image: serenalin7749/udagram-api-feed
  frontend:
    build:
      context: ./udagram-frontend
    image: serenalin7749/udagram-frontend:local
