apiVersion: v1
kind: Service
metadata:
  name: udagram-frontend
  labels:
    service: udagram-frontend
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    service: udagram-frontend
    run: udagram-frontend
